In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


Load dataset


In [3]:
df = pd.read_csv("../data/raw/Student_Performance.csv")
df.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

Inspecting  structure

In [4]:
df.describe()


Hours Studied  Previous Scores   Sleep Hours  \
count   10000.000000     10000.000000  10000.000000   
mean        4.992900        69.445700      6.530600   
std         2.589309        17.343152      1.695863   
min         1.000000        40.000000      4.000000   
25%         3.000000        54.000000      5.000000   
50%         5.000000        69.000000      7.000000   
75%         7.000000        85.000000      8.000000   
max         9.000000        99.000000      9.000000   

       Sample Question Papers Practiced  Performance Index  
count                      10000.000000       10000.000000  
mean                           4.583300          55.224800  
std                            2.867348          19.212558  
min                            0.000000          10.000000  
25%                            2.000000          40.000000  
50%                            5.000000          55.000000  
75%                            7.000000          71.000000  
max                            9.000000         100.000000

In [5]:
df.info()


<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Hours Studied                     10000 non-null  int64  
 1   Previous Scores                   10000 non-null  int64  
 2   Extracurricular Activities        10000 non-null  str    
 3   Sleep Hours                       10000 non-null  int64  
 4   Sample Question Papers Practiced  10000 non-null  int64  
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), str(1)
memory usage: 468.9 KB


In [6]:
df.shape


(10000, 6)

In [10]:
columns = df.columns

for col in columns:
    print("----------------------------------------")
    print(col)
    print(df[col].isna().sum())
    print(df[col].unique())
    print("----------------------------------------")


----------------------------------------
Hours Studied
0
[7 4 8 5 3 6 2 1 9]
----------------------------------------
----------------------------------------
Previous Scores
0
[99 82 51 52 75 78 73 45 77 89 91 79 47 72 83 54 96 74 85 61 62 84 94 90
 44 70 67 97 59 55 68 63 46 76 43 81 93 98 48 92 64 88 60 87 40 69 80 95
 49 50 53 71 56 58 66 65 57 41 42 86]
----------------------------------------
----------------------------------------
Extracurricular Activities
0
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
----------------------------------------
----------------------------------------
Sleep Hours
0
[9 4 7 5 8 6]
----------------------------------------
----------------------------------------
Sample Question Papers Practiced
0
[1 2 5 6 0 8 3 4 9 7]
----------------------------------------
----------------------------------------
Performance Index
0
[ 91.  65.  45.  36.  66.  61.  63.  42.  69.  84.  73.  27.  33.  68.
  43.  67.  70.  30.  71.  85.  57.  35.  49.  83.  74. 